---
title: "BPDArrests"
author: "Zachary Moss"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.align = "center",
                      message = F,
                      warning = F)

# Loading in the needed packages
pacman::p_load(readxl, tidyverse, ggplot2, lubridate)

# Changing default themes
theme_set(theme_bw())
theme_update(plot.title = element_text(hjust = 0.5),
             plot.subtitle = element_text(hjust = 0.5))

# Changing the default choice for how many decimal places are displayed
options(digits = 4)

trafficstops <- read.csv("Traffic_Stops.csv")
```

## Getting the Data


```{r data cleaning}
traffic_clean <- 
  trafficstops %>% 
  mutate(call = ymd_hms(call_time),
         month = month(call, label = T),     # Keep just the month with the name of month (label = T)
         weekday = wday(call, label = TRUE), # Keep the day of the week with name
         hour = hour(call),                  # Keeps just the hour
         minute = minute(call),              # Keeps just the minute    
         date = date(call),                  # Keeps just the date - no time
         day = yday(call)                    # Returns the day of the year (Dec 31st = 365)
  ) %>% 
  
  select(
    incident_number, call_type, call, day, race, gender, age, stop_type, stop_outcome, veh_state, count_tickets, count_warnings, search, search_type, arrest, arrest_warrant)

traffic_clean
```


```{r race and age}
traffic_clean %>% 
  group_by(stop_outcome) %>% 
  summarise(avg_age = mean(age, na.rm = T)) %>% 
  
  ggplot(
    mapping = aes(
      x = fct_reorder(stop_outcome, avg_age, .fun = min),
      y = avg_age)
  ) + 
  
  geom_col(
    fill = c("tomato", "steelblue", "seagreen", "orchid", "brown4")
  ) +
  
  scale_y_continuous(
    expand = c(0, 0, .08, 0)
  ) +
  
  theme_minimal() +
  
  labs(
    y = "Average Age",
    x = "Stop Outcome",
    title = "Stop Outcome based on Age"
  ) +
  
  theme(
    plot.title = element_text(hjust = .5)
  ) -> ts_base

ts_base
```

```{r arrests or tickets = true}
traffic_arrests <- 
  trafficstops %>% 
  filter(stop_outcome == "A = Arrest for Violation" | stop_outcome == "T = Ticket" )

tibble(traffic_arrests)


traffic_arrests %>% 
  ggplot(mapping = aes(
    x = stop_outcome
    )
  ) +
  
  geom_col() +
  
  scale_y_continuous(
    expand = c(0, 0, .05, 0)
  )

```
```{state}
trafficstops|>
  



```

